### ISSUE TITLE
Add option to set bundle comment

### ISSUE THREAD

**Issue by tomhelmer** [contentful/actions-app-deploy#27]
Hi, It would be nice if I could set a bundle comment when running the action.

```
 - uses: contentful/actions-app-deploy@v1
        with:
          organization-id: ${{ secrets.ORGANIZATION_ID }}
          app-definition-id: ${{ secrets.APP_DEFINITION_ID }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          folder: build
          comment: "Deployed by github action"
```
